# Generated by Django 2.2.24 on 2021-10-05 23:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='messageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'messageContent',
            },
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(default='static/default.jpg', upload_to='uploads/%Y/%m/%d/', verbose_name='头像')),
                ('sex', models.CharField(max_length=2, null=True, verbose_name='性别')),
                ('contact', models.CharField(max_length=11, null=True, verbose_name='联系方式')),
                ('signature', models.CharField(max_length=11, null=True, verbose_name='个性签名')),
                ('school', models.CharField(max_length=11, null=True, verbose_name='学校')),
                ('networkTime', models.IntegerField(default=0)),
                ('active', models.PositiveIntegerField(default=0, editable=False)),
                ('followeds', models.PositiveIntegerField(default=0, editable=False)),
                ('followings', models.PositiveIntegerField(default=0, editable=False)),
                ('articles', models.PositiveIntegerField(default=0, editable=False)),
                ('comments', models.PositiveIntegerField(default=0, editable=False)),
                ('likes', models.PositiveIntegerField(default=0, editable=False)),
                ('collects', models.PositiveIntegerField(default=0, editable=False)),
                ('directMessages', models.PositiveIntegerField(default=0, editable=False)),
                ('messages', models.PositiveIntegerField(default=0, editable=False)),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userProfile',
            },
        ),
        migrations.CreateModel(
            name='follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followTime', models.DateTimeField(default=datetime.datetime.now)),
                ('message', models.CharField(default='22', max_length=2)),
                ('followed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='followed', to='users.userProfile')),
                ('following', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='following', to='users.userProfile')),
            ],
            options={
                'db_table': 'follow',
            },
        ),
    ]
