# Generated by Django 2.2.24 on 2021-10-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211008_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='message',
            field=models.CharField(default='22', max_length=2),
        ),
    ]
