# Generated by Django 2.2.24 on 2021-10-08 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='message',
        ),
    ]
