# Generated by Django 2.2.24 on 2021-10-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userprofile_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='newFlag',
            field=models.CharField(default='0', max_length=2, verbose_name='新人'),
        ),
    ]
