# Generated by Django 2.2.24 on 2021-10-14 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_newflag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='newFlag',
        ),
    ]
