# Generated by Django 2.2.24 on 2021-10-05 23:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(default='')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now)),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('likes', models.PositiveIntegerField(default=0, editable=False)),
                ('collects', models.PositiveIntegerField(default=0, editable=False)),
                ('comments', models.PositiveIntegerField(default=0, editable=False)),
                ('articleTags', models.ManyToManyField(related_name='articleTags', to='tags.tag')),
                ('postMan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.userProfile')),
            ],
            options={
                'db_table': 'article',
                'ordering': ['-createTime'],
            },
        ),
        migrations.CreateModel(
            name='articleView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewTime', models.DateTimeField(default=datetime.datetime.now)),
                ('viewArticle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='viewArticle', to='article.article')),
                ('viewMan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.userProfile')),
            ],
            options={
                'db_table': 'articleView',
            },
        ),
        migrations.CreateModel(
            name='articleLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeTime', models.DateTimeField(default=datetime.datetime.now)),
                ('likeArticle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='article.article')),
                ('likeMan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.userProfile')),
            ],
            options={
                'db_table': 'articleLike',
            },
        ),
        migrations.CreateModel(
            name='articleCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectTime', models.DateTimeField(default=datetime.datetime.now)),
                ('collectArticle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='article.article')),
                ('collectMan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.userProfile')),
            ],
            options={
                'db_table': 'articleCollect',
            },
        ),
    ]
