# Generated by Django 2.2.24 on 2021-10-14 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='postMan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userProfile'),
        ),
    ]
