# Generated by Django 2.2.24 on 2021-10-05 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(error_messages={'yonghuming': '长度必须为'}, max_length=64, verbose_name='标签名')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('tagCreater', models.CharField(default='', error_messages={'yonghuming': '长度必须为'}, max_length=64, verbose_name='用户名')),
            ],
            options={
                'db_table': 'tag',
            },
        ),
    ]
