# Generated by Django 2.2.24 on 2021-10-19 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_userprofile_newflag'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='nowCommentLikeFlag',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='nowCommentLikeNumber',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parentArticleId',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='likeCommentId',
        ),
        migrations.AddField(
            model_name='comment',
            name='commentLikes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='likeComment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='likeComment', to='comment.comment'),
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='likeMan',
        ),
        migrations.AddField(
            model_name='commentlike',
            name='likeMan',
            field=models.ManyToManyField(to='users.userProfile'),
        ),
    ]
