# Generated by Django 2.2.24 on 2021-10-20 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_userprofile_newflag'),
        ('comment', '0003_commentlike_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='likeComment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='commentLike', to='comment.comment'),
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='likeMan',
        ),
        migrations.AddField(
            model_name='commentlike',
            name='likeMan',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='commentLikeUser', to='users.userProfile'),
        ),
    ]
