# Generated by Django 2.2.24 on 2021-10-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20211020_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlike',
            name='article',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='likeComment',
        ),
        migrations.AddField(
            model_name='commentlike',
            name='likeComment',
            field=models.ManyToManyField(default='', related_name='commentLikeParent', to='comment.comment'),
        ),
    ]
