# Generated by Django 2.2.24 on 2021-10-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_auto_20211020_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlike',
            name='likeComment',
        ),
        migrations.AddField(
            model_name='comment',
            name='commentLikeMan',
            field=models.ManyToManyField(default='', related_name='commentLikeMan', to='comment.commentLike'),
        ),
    ]
