# Generated by Django 2.2.24 on 2021-10-20 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_auto_20211020_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentLikeMan',
        ),
        migrations.AddField(
            model_name='commentlike',
            name='likeComment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='likeComment', to='comment.comment'),
        ),
    ]
