# Generated by Django 2.2.24 on 2021-10-20 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20211014_2338'),
        ('comment', '0007_auto_20211020_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='parentArticle',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='parentArticle', to='article.article'),
        ),
    ]
